### ISSUE TITLE
Move namespace

### ISSUE THREAD

**Issue by kinncj** [kinncj/forker#9]
@netojoaobatista and @henriquemoody , what do you think to move this as a PHPBR.org tool, and start to build a PHPBR namespace?

**Comment by henriquemoody** [comment]
:+1:

**Comment by henriquemoody** [comment]
My :+1: is more like: _I will not oppose if you do_.

To be more clear, I don't think that makes much sense so let me explain why:
- I don't know exactly what @php-brasil represents as an organization (is that only about the Facebook community?)
- Seems everything in @php-brasil is written in Portuguese (because it makes sense) but what is going to happen to this project?
- I don't think @php-brasil's users are going to agree with this migration and a voting is required for that (see also php-brasil/Documentos#14).

Whatever, that decision cannot be made here.

**Comment by malukenho** [comment]
@henriquemoody :+1:

**Comment by kinncj** [comment]
- I don't know exactly what @php-brasil represents as an organization (is that only about the Facebook community?)
  - Represents the community by it-self (not only FB)
- Seems everything in @php-brasil is written in Portuguese (because it makes sense) but what is going to happen to this project?
  - IMHO, any piece of code must be done in the most used language, english.
- I don't think @php-brasil's users are going to agree with this migration and a voting is required for that (see also php-brasil/Documentos#14).
  - I agree, and that's why I decide to move back with my opinion and keep under the _kinncj_ namespace... I was thinking about _PHPFluent_, but this does not correspond to that namespace objectives... I just want to find a better namespace than my own to spread this tool.

**Comment by malukenho** [comment]
**Represents the community by it-self (not only FB)**

So, I think IMO @php-brasil is only a extension for phpsp-ug.
See the `community` section on  [phpbr](http://phpbr.org).
Its don't represents me.
How about another communities? Excluded?

And same in FB group... Has anyone from `php-pb`? 

Well, I don't know.

/cc @kinncj @henriquemoody

**Comment by henriquemoody** [comment]
> Represents the community by it-self (not only FB)

I don't think @php-brasil represents the community as well but just another Facebook group (which I disagree in many aspects).

> How about another communities? Excluded?

In this point I have to disagree with @malukenho because I'm sure they are open for any community since these communities want to join.

I'm closing this issue since the majority decided the project will stay in @kinncj's namespace.
~
@malukenho if is that your wish  feel free to [create an issue](https://github.com/php-brasil/Documentos/issues/new) to discuss about it in the @php-brasil organization.

**Comment by kinncj** [comment]
The "website" is just a dunmy site. At least if yoy read it, it looks like

**Comment by kinncj** [comment]
It does represent. The repo is used to define the rules for the fb group.
But will be migrate to the forum and mail list. Anyway, is something that
they should discuss, not us.

**Comment by malukenho** [comment]
@kinncj @henriquemoody Okay. Thanks

**Comment by henriquemoody** [comment]
Thank you @malukenho for share your thoughts, I really appreciate that.
